infra: add failing workflow if invalid signature

diff --git a/.github/workflows/test-readme-steps.yml b/.github/workflows/test-readme-steps.yml
--- a/.github/workflows/test-readme-steps.yml
+++ b/.github/workflows/test-readme-steps.yml
@@ -58,6 +58,19 @@ jobs:
       with:
         crate: c2patool
         
-    - name: Verify Signed Image
+    - name: Validate Signed Image
       run: |
-        c2patool signed_test_image.jpg
+        echo "$(c2patool signed_test_image.jpg)" >> validation_results.json
+
+    - name: Download jq and Get validation results
+      id: validation_check
+      run: |
+        sudo apt install jq
+        echo "validation_results=$(jq -r .validation_state validation_results.json)" >> $GITHUB_OUTPUT
+
+    - name: Fail if validation failed
+      if: ${{ steps.validation_check.outputs.validation_results == 'Invalid' }}
+      run: |
+        echo "Invalid C2PA signature"
+        exit 1
+
